server:
  port: 8080
  readTimeout: 30s
  writeTimeout: 120s
  idleTimeout: 60s

router:
  stickinessWindow: 60s
  healthCheckInterval: 30s
  maxLatencyMs: 5000
  maxQueueDepth: 10
  overheadFactor: 1.1
  metricsUpdateInterval: 30s
  routingStrategy: hybrid
  enableExternalFallback: true
  clusterCostThreshold: 0.01

# Mock clusters for demo
clusters:
  - name: aws-demo-cluster
    endpoint: https://demo.aws.cluster
    region: us-east-1
    provider: aws
    costPerHour: 0.05
    authType: hmac
    sharedSecret: demo-secret
    
  - name: gcp-demo-cluster
    endpoint: https://demo.gcp.cluster
    region: us-central1
    provider: gcp
    costPerHour: 0.04
    authType: hmac
    sharedSecret: demo-secret

  - name: azure-demo-cluster
    endpoint: https://demo.azure.cluster
    region: eastus
    provider: azure
    costPerHour: 0.06
    authType: hmac
    sharedSecret: demo-secret

# External providers
externalProviders:
  - name: openai
    type: openai
    enabled: true
    apiKey: "${OPENAI_API_KEY}"
    defaultModel: gpt-3.5-turbo
    rateLimit:
      requestsPerMinute: 3500
      tokensPerMinute: 90000
      burstMultiplier: 1.5

  - name: claude
    type: claude
    enabled: true
    apiKey: "${ANTHROPIC_API_KEY}"
    defaultModel: claude-3-haiku-20240307
    rateLimit:
      requestsPerMinute: 1000
      tokensPerMinute: 100000
      burstMultiplier: 1.2
      
  - name: gemini
    type: gemini
    enabled: true
    apiKey: "${GEMINI_API_KEY}"
    defaultModel: gemini-1.5-flash
    rateLimit:
      requestsPerMinute: 1500
      tokensPerMinute: 32000
      burstMultiplier: 1.3