apiVersion: v2
name: platform
description: Core platform components (ingress, cert-manager, prometheus)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingressNginx.enabled
  - name: cert-manager
    version: "v1.13.2"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
  - name: kube-prometheus-stack
    version: "54.0.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
